### PR TITLE
Simplify the Pos class

### PR DESCRIPTION
**Pull request by aliciawyy**
Hi,

I found your project by accident on github and it looks quite interesting! Just when reading the code, I noticed that some details can be simplified to make the code more readable and speed-up a little (like remove the nested if else and list append in the Pos class). Do you mind to take a look if you want to merge this PR ?

Best,
Alice

### CODE REVIEW

**Comment by voaneves** [comment]
Hi there!

Did you %timeit how big was the speed improvement?

**Comment by chynl** [comment]
Thank you for the contribution, I am expecting more optimizations on the strategy or bugs fixing though. And it seems that the changes will not affect much of the algorithm performance. :)

**Comment by aliciawyy** [comment]
Hi,

I didn’t measure. I just started reading the code. The function adj or direct_to should be called many times as it’s the basic structure of this code. Isn’t is better to have a O(1) operation than the nested if else O(n) ? It’s also more clear and less error prone as the bijection is now handled in one structure and the code is simpler. And the python for loop with append is much less efficient than generator. 

As the list is short, the optimisation is small but when you run it ten thousands of times it will help. That’s the point of view of a python developer. Of course from the point of view of a data scientist that only the algorithm counts, I think you dont need to consider these low level python details.

**Comment by chynl** [comment]
Why nested if else is O(n)?

**Comment by aliciawyy** [comment]
Sorry, I wasn't so precise. The list append in Python works in a way that every time you append you copy the original values to a new list than add the new value appended to the new list. This part is not efficient.
For the nested if else, it adds the code complexity and can be error prone as the bijection of the two functions are manually coded to be matched. When one part is changed, you need to be very careful to match the other part. This is generally not so good for production code.

**Comment by chynl** [comment]
Thanks. I understand you point. Still I am expecting contribution to the strategy and the inefficient appending to list is not the performance bottleneck of current agent's strategy so I am not going to merge your pull request. Hope you can understand it. Sorry.

**Pull request closed without merging**
